const pool=require('../db');
const {supabaseAdmin,supabase}=require('../config/supabase');
const {sendOtpEmail}=require('../config/mailer');
const profiles=require('./pgProfileController');
const disposableDomains=require('disposable-email-domains');
const extra=new Set(['tempmail.com','temp-mail.com','throwaway.email','throwawaymail.com','trashmail.com','fakeinbox.com','yopmail.com','sharklasers.com','grr.la','guerrillamailblock.com','spam4.me','emailondeck.com','tempinbox.com','discard.email','discardmail.com','spambox.us','tempr.email','getairmail.com','moakt.com','mohmal.com','mytemp.email','tempsky.com','mintemail.com','momentics.ru']);
function validEmail(email){const domain=email.split('@')[1]?.toLowerCase();return domain&&!disposableDomains.includes(domain)&&!extra.has(domain);}
async function getAuthUser(email){let page=1;while(true){const {data,error}=await supabaseAdmin.auth.admin.listUsers({page,perPage:1000});if(error)throw error;const user=data?.users?.find(u=>u.email?.toLowerCase()===email);if(user)return user;if(!data?.users?.length||data.users.length<1000)return null;page++;}}
exports.sendOtp=async(req,res)=>{try{const email=String(req.body?.email||'').trim().toLowerCase();if(!email)return res.status(400).json({error:'Email is required'});if(!validEmail(email))return res.status(400).json({error:'Please use a valid, non-temporary email address.'});if(!supabaseAdmin)return res.status(500).json({error:'Auth service is not configured'});const otp=String(Math.floor(100000+Math.random()*900000));const expiresAt=new Date(Date.now()+10*60*1000);await pool.query(`INSERT INTO otp_verifications(email,otp,expires_at,verified) VALUES($1,$2,$3,false) ON CONFLICT(email) DO UPDATE SET otp=EXCLUDED.otp,expires_at=EXCLUDED.expires_at,verified=false,created_at=now()`,[email,otp,expiresAt]);await sendOtpEmail(email,otp);res.json({message:'OTP sent. Please check your inbox and spam folder.'});}catch(e){console.error('[pg send otp]',e.message);res.status(500).json({error:'Could not send verification email'});}};
exports.verifyOtp=async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),code=String(req.body?.otp||'').trim();if(!email||!code)return res.status(400).json({error:'Email and OTP are required'});const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM otp_verifications WHERE email=$1 FOR UPDATE',[email]);const otp=rows[0];if(!otp||otp.otp!==code){await client.query('ROLLBACK');return res.status(400).json({error:'Invalid OTP. Please check and try again.'});}if(new Date(otp.expires_at)<=new Date()){await client.query('ROLLBACK');return res.status(400).json({error:'OTP has expired. Request a new one.'});}await client.query('UPDATE otp_verifications SET verified=true WHERE email=$1',[email]);await client.query('COMMIT');const existing=await getAuthUser(email);const tempPassword=`OTP_${cryptoRandom()}_${Date.now()}`;let userId;if(existing){userId=existing.id;const {error}=await supabaseAdmin.auth.admin.updateUserById(userId,{password:tempPassword,email_confirm:true});if(error)throw error;}else{const {data,error}=await supabaseAdmin.auth.admin.createUser({email,password:tempPassword,email_confirm:true});if(error)throw error;userId=data.user.id;const base=email.split('@')[0].toLowerCase().replace(/[^a-z0-9_]+/g,'_').slice(0,20)||'user';let username=base;let n=0;while((await pool.query('SELECT 1 FROM profiles WHERE username=$1',[username])).rowCount)username=`${base}_${++n}`;await pool.query(`INSERT INTO profiles(id,email,username,full_name) VALUES($1,$2,$3,'') ON CONFLICT(id) DO NOTHING`,[userId,email,username]);}const {data:sessionData,error:signInError}=await supabase.auth.signInWithPassword({email,password:tempPassword});if(signInError)throw signInError;res.json({message:'OTP verified successfully',session:sessionData.session,user:sessionData.user});}catch(e){try{await client.query('ROLLBACK');}catch{}console.error('[pg verify otp]',e.message);res.status(500).json({error:'Could not verify OTP'});}finally{client.release();}};
function cryptoRandom(){return require('crypto').randomBytes(18).toString('hex');}
